# deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-db-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db-app
  template:
    metadata:
      labels:
        app: db-app
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017

        - name: db-app
          image: rupeshs11/mongo-demo:100
          env:
            - name: MONGO_URL
              value: mongodb://localhost:27017
          ports:
            - containerPort: 3000

---
# service.yml 
apiVersion: v1
kind: Service
metadata:
  name: service-my-db-app
spec:
  type: NodePort
  selector:
    app: db-app
  ports:
    - port: 80
      targetPort: 3000

